FROM ubuntu

RUN apt-get update && apt-get install -y automake autotools-dev git make gcc \
    indent libtool iproute2

USER 1000:1000

WORKDIR /slirp4netns

CMD ["bash", "-c", "hack/indent.sh && \
    test -z \"$(git diff)\" && \
    ./autogen.sh && \
    ./configure && \
    make -j \"$(nproc)\" && \
    make -j \"$(nproc)\" distcheck"]
